#pragma once
// Generated by build script, do not edit!
#define UNITY_VERSION_FULL "2018.4.16f1_e6e9ca02b32a"
#define UNITY_VERSION_FULL_NICE "2018.4.16f1 (e6e9ca02b32a)"
#define UNITY_VERSION_BLD 15133130
#define UNITY_VERSION_DATE 1579703394
#define UNITY_VERSION_WIN "2018.4.16.15133130"
#define UNITY_VERSION_BRANCH "2018.4/release"
